---
slug: :list_settings
depends:
  mikutter: '3.1'
  plugin:
  - list
  - settings
  - gui
  - gtk
  - uitranslator
  - skin
version: '1.0'
author: toshi_a
name: リスト設定
description: リストの管理機能を提供し、設定画面から追加・削除・変更をできるようにします
